
package Vista;


import Modelo.Arbitro;
import Modelo.ListModelPersonalizado;

/**
 *
 * @author Andre
 */
public class RegistroSeleccionArbitro extends javax.swing.JDialog {

    public ListModelPersonalizado<Arbitro> listaArbitros = new ListModelPersonalizado();
    /**
     * Creates new form DialogNacionalidad
     * @param parent
     * @param modal
     */
    public RegistroSeleccionArbitro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        logoPrinicipal = new javax.swing.JLabel();
        txtLista = new javax.swing.JLabel();
        txtListado = new javax.swing.JLabel();
        jbtnAsignar = new javax.swing.JButton();
        listado = new javax.swing.JScrollPane();
        jlistArbitros = new javax.swing.JList<>();
        jlblEquipoLocal = new javax.swing.JLabel();
        jlblEquipoVisitante = new javax.swing.JLabel();
        txtVS = new javax.swing.JLabel();
        txtNuevo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelSuperior.setBackground(new java.awt.Color(0, 51, 112));

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        logoPrinicipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoPrinicipal.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\logoAsignarArbitro.png"));

        txtLista.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        txtLista.setForeground(new java.awt.Color(0, 51, 112));
        txtLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLista.setText("ASIGNAR ARBITRO");

        txtListado.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        txtListado.setForeground(new java.awt.Color(153, 153, 153));
        txtListado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtListado.setText("LISTADO DE ARBITROS");

        jbtnAsignar.setBackground(new java.awt.Color(255, 102, 0));
        jbtnAsignar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jbtnAsignar.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\logoRegistrar.png"));
        jbtnAsignar.setContentAreaFilled(false);
        jbtnAsignar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlistArbitros.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jlistArbitros.setModel(listaArbitros);
        jlistArbitros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listado.setViewportView(jlistArbitros);

        jlblEquipoLocal.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jlblEquipoLocal.setForeground(new java.awt.Color(255, 153, 0));
        jlblEquipoLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblEquipoLocal.setText("ELEGIR EQ1");

        jlblEquipoVisitante.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jlblEquipoVisitante.setForeground(new java.awt.Color(255, 153, 0));
        jlblEquipoVisitante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblEquipoVisitante.setText("ELEGIR EQ2");

        txtVS.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        txtVS.setForeground(new java.awt.Color(255, 153, 0));
        txtVS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtVS.setText("VS");

        txtNuevo.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        txtNuevo.setForeground(new java.awt.Color(153, 153, 153));
        txtNuevo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNuevo.setText("ASIGNAR ARBITRO");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPrinicipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(txtLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(txtNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtListado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listado)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(jlblEquipoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblEquipoVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(27, 27, 27))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPrinicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLista)
                .addGap(31, 31, 31)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEquipoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblEquipoVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(txtListado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnAsignar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JButton jbtnAsignar;
    public javax.swing.JLabel jlblEquipoLocal;
    public javax.swing.JLabel jlblEquipoVisitante;
    public javax.swing.JList<String> jlistArbitros;
    private javax.swing.JScrollPane listado;
    private javax.swing.JLabel logoPrinicipal;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JLabel txtLista;
    private javax.swing.JLabel txtListado;
    private javax.swing.JLabel txtNuevo;
    private javax.swing.JLabel txtVS;
    // End of variables declaration//GEN-END:variables
}
